# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LetsMeet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LetsMeet
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'
	pod 'Firebase/Messaging'
	pod 'Firebase/Storage'	
	pod 'Firebase/Analytics'

	pod 'Gallery'

	pod 'Gallery'

	pod 'NVActivityIndicatorView/AppExtension'
	pod 'ProgressHUD'
	pod 'SKPhotoBrowser'
	pod 'Shuffle-iOS'

	pod 'MessageKit'
	pod 'InputBarAccessoryView'	

	pod 'IQKeyboardManagerSwift'	
end
